# Generated by Django 3.0.8 on 2020-09-19 15:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200917_2225'),
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupcoveragedistrict',
            options={'verbose_name': 'Pickup District', 'verbose_name_plural': 'Pickup Districts'},
        ),
        migrations.AlterModelOptions(
            name='pickupcoveragezone',
            options={'verbose_name': 'Pickup Zone', 'verbose_name_plural': 'Pickup Zones'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Cash Collection Amount', max_digits=12, verbose_name='Cash Collection Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_deliverd_by', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_individual',
            field=models.BooleanField(default=False, verbose_name='Is individual Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickedup_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_pickedup_by', to='customers.Customer'),
        ),
    ]
