# Generated by Django 3.0.8 on 2020-10-01 23:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20200919_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.00'), max_digits=5, verbose_name='Product Weight'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12, verbose_name='Service Charge'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_deliverd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickedup_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_pickedup_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier', unique=True, verbose_name='UUID')),
                ('is_available', models.BooleanField(default=True, help_text='if False the record is not available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked', 'Picked'), ('in_hub', 'In Hub'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], max_length=80)),
                ('pre_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked', 'Picked'), ('in_hub', 'In Hub'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], max_length=80, verbose_name='Previous Status')),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker', to=settings.AUTH_USER_MODEL)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
