# Generated by Django 3.0.8 on 2020-09-13 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier', unique=True, verbose_name='UUID')),
                ('is_available', models.BooleanField(default=True, help_text='if False the record is not available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Business name', max_length=255)),
                ('phone', models.CharField(help_text='Business Phone number', max_length=15)),
                ('pickup_phone', models.CharField(blank=True, help_text='Pickup Phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Business email address', max_length=254)),
                ('address', models.CharField(help_text='Business address', max_length=255)),
                ('pickup_address', models.CharField(blank=True, help_text='Pickup address', max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], max_length=50)),
                ('withdrawal', models.CharField(choices=[('as_per_request', 'As per Request'), ('daily', 'Daily'), ('weekly', 'weekly'), ('bi-weekly', 'BI-Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('website', models.CharField(blank=True, help_text='Business website address', max_length=255)),
                ('social_media', models.CharField(blank=True, help_text='Business social media', max_length=255)),
                ('referral_number', models.CharField(blank=True, max_length=15)),
                ('verification_number', models.CharField(blank=True, help_text='NID, Passport or Trade License.', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='orders.PickupCoverageZone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier', unique=True, verbose_name='UUID')),
                ('is_available', models.BooleanField(default=True, help_text='if False the record is not available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_option', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], default='cash', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Mobile account number', max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=60)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(blank=True, max_length=15)),
                ('account_holder_name', models.CharField(blank=True, max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='customers.Customer')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentinfo',
            index=models.Index(fields=['payment_option'], name='customers_p_payment_c816d5_idx'),
        ),
    ]
