# Generated by Django 3.0.8 on 2020-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='withdrawal',
            field=models.CharField(choices=[('as_per_request', 'As per Request'), ('daily', 'Daily'), ('weekly', 'weekly'), ('bi-weekly', 'BI-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=50),
        ),
    ]
